name: Create Timestamped File

on:
  schedule:
    - cron: '*/1 * * * *'  # 매 1분마다 실행
  workflow_dispatch:        # 수동 실행도 가능

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run script
        run: python run.py

      - name: Commit output file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add hello_*.txt
          git commit -m "Add timestamped hello file"
          git push
