name: Manual Python Run

on:
  workflow_dispatch:  # 수동 실행 버튼 활성화

permissions:
  contents: write  # commit/push하려면 필요

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run script
        run: python run.py

      - name: Commit result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add hello_*.txt
          git commit -m "Manual run result" || echo "No changes"
          git push
