name: Run

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages  # ✅ 이 부분 추가
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run script
        run: python kiwoom_favorite.py

      - name: Git commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "자동 업데이트된 HTML" || echo "No changes"
          git push

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # 현재 디렉토리 (kiwoom_rank_viewer.html 포함)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
