name: Scheduled Python Run

on:
  schedule:
    - cron: '*/5 * * * *'  # 5분마다 실행 (지연 방지 차원에서 1분 대신 권장)
  workflow_dispatch:        # 수동 실행 버튼 추가

permissions:
  contents: write  # commit push 허용

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run script
        run: python run.py

      - name: Commit output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add hello_*.txt
          git commit -m "Update output" || echo "No changes"
          git push
